# replace with `bosh status --uuid`
director_uuid: CHANGE_ME
azs:
  - CHANGE_ME
network_name: CHANGE_ME

nginx:
  vm_type: micro
  vm_password: echo -n 'YOUR_PASSWORD' | mkpasswd --method=sha-512 --password-fd=0
  static_ips: 10.0.0.1
  local_properties:
    ssl_only: false
    grafana:
      https_port: 443

grafana:
  vm_type: micro
  vm_password: echo -n 'YOUR_PASSWORD' | mkpasswd --method=sha-512 --password-fd=0
  persistent_disk_type: 1024
  admin_password: CHANGE_ME
alertmanager:
  vm_type: micro
  vm_password: echo -n 'YOUR_PASSWORD' | mkpasswd --method=sha-512 --password-fd=0
  persistent_disk_type: 1024
  receivers:
    - name: default-receiver
      slack_configs:
        - api_url: https://hooks.slack.com/services/....
          channel: 'slack-channel'
          send_resolved: true
          pretext: "text before the actual alert message"
          text: "hello"
prometheus:
  vm_type: micro
  vm_password: echo -n 'YOUR_PASSWORD' | mkpasswd --method=sha-512 --password-fd=0
  persistent_disk_type: 5120

bosh_exporter:
  bosh:
    uaa:
      url: https://BOSH_DIRECTOR:8443
      client_id: prometheus-bosh
      client_secret: prometheus-client-secret
    url: https://BOSH_DIRECTOR
    ca_cert: |
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----

firehose_exporter:
  uaa:
    url: https://uaa.SYSTEM_DOMAIN
    client_id: prometheus-firehose
    client_secret: prometheus-client-secret
  doppler:
    url: wss://doppler.SYSTEM_DOMAIN
  web:
    port: 9186
  skip_ssl_verify: true

cf_exporter:
  cf:
    api_url: https://api.SYSTEM_DOMAIN
    client_id: prometheus-cf
    client_secret: prometheus-client-secret
  skip_ssl_verify: true

mysqld_exporter:
  mysql:
    address: CHANGE_ME
    username: exporter
    password: CHANGE_ME
